import os
import random
import numpy as np
from PIL import Image, ImageOps

# Settings
PAGE_WIDTH = 800
PAGE_HEIGHT = 1000
START_X = 50
START_Y = 80
LINE_HEIGHT = 60

glyph_path = "glyphs"
background_path = "backgrounds/ruled.png"
output_path = "output/page1.png"

# Load background
background = Image.open(background_path).convert("RGB")
page = background.copy()

x = START_X
y = START_Y

text = "This is my handwritten assignment generated by AI"

for char in text:
    
    if char == " ":
        x += random.randint(20, 40)
        continue
    
    folder = os.path.join(glyph_path, char)
    
    if not os.path.exists(folder):
        continue
    
    files = os.listdir(folder)
    file = random.choice(files)
    
    glyph = Image.open(os.path.join(folder, file)).convert("RGBA")
    
    # Random rotation
    angle = random.uniform(-3, 3)
    glyph = glyph.rotate(angle, expand=True)
    
    # Random scaling
    scale = random.uniform(0.9, 1.1)
    w, h = glyph.size
    glyph = glyph.resize((int(w*scale), int(h*scale)))
    
    # Baseline shift
    y_offset = random.randint(-5, 5)
    
    page.paste(glyph, (x, y + y_offset), glyph)
    
    x += glyph.size[0] + random.randint(2, 8)
    
    # Line break
    if x > PAGE_WIDTH - 100:
        x = START_X
        y += LINE_HEIGHT

# Save output
page.save(output_path)
print("Handwritten page generated!")